-- Create the Learning Management System (LMS) Modules table
create table lms_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tags text[], -- Array of strings for categorization (e.g., ['security', 'telegram'])
  is_trending boolean default false,
  image_url text, -- Optional: URL to a cover image
  content_url text, -- Optional: URL to the full article or PDF
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PROPOSED MOCK DATA INSERTION (For Testing)
insert into lms_modules (title, description, tags, is_trending)
values 
  ('Telegram Security 101', 'How to hide your phone number and stop message forwarding.', ARRAY['telegram', 'privacy'], true),
  ('Recognizing Love Bombing', 'Early signs of manipulation in relationships.', ARRAY['relationships', 'abuse'], true),
  ('Digital Evidence Collection', 'How to legally document harassment for police reports.', ARRAY['legal', 'evidence'], false);
