-- Existing Schema content...

-- ==========================================
-- SPRINT 3: THE PULSE (COMMUNITY TRENDS)
-- ==========================================

create table if not exists community_trends (
  id bigint generated by default as identity primary key,
  category text not null, -- 'NCII', 'Blackmail', 'Phishing'
  alert_text text not null, -- 'High reports of...', 'New scam alert...'
  severity text check (severity in ('High', 'Medium', 'Low')) default 'Medium',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Public Read. Only Service Role can write (via backend script).
alter table community_trends enable row level security;

create policy "Public can view active trends"
on community_trends for select
using ( is_active = true );
